export const T = {
  title: "Mimic Party Mini",
  prompt: (p) => `“${p}”`,

  menu: {
    nickname: "Takma adın",
    nicknamePlaceholder: "ör. Batu",
    create: "Oda kur",
    join: "Katıl",
    roomCode: "Oda kodu",
    or: "ya da bir odaya katıl",
    randomize: "Rastgele",
    body: "Gövde",
    color: "Renk",
    eyes: "Gözler",
    hat: "Aksesuar",
    needName: "Önce bir takma ad yaz.",
    needCode: "5 karakterlik oda kodunu yaz.",
  },

  avatar: {
    body: ["Fasulye", "Kutu", "Koni", "Top"],
    eyes: ["Yuvarlak", "Uykulu", "Kızgın", "Fıldır"],
    hat: ["Yok", "Kep", "Parti şapkası", "Taç", "Kulaklık", "Fiyonk"],
  },

  lobby: {
    roomCode: "Oda kodu",
    copyCode: "Kodu kopyala",
    copyLink: "Linki kopyala",
    copied: "Kopyalandı!",
    players: (n) => `Oyuncular ${n}/6`,
    cycles: "Herkes kaç kez sahneye çıksın?",
    cyclesOption: (c) => `${c}×`,
    start: "Oyunu başlat",
    needPlayers: "Başlamak için en az 2 oyuncu gerekli.",
    waitingHost: (name) => `${name} oyunu başlatacak…`,
    editAvatar: "Karakterini düzenle",
    done: "Tamam",
    leave: "Odadan çık",
  },

  mic: {
    title: "Mikrofon",
    test: "Mikrofonu test et",
    select: "Mikrofon",
    denied: "Mikrofon izni verilmedi. Adres çubuğundaki kilit simgesinden izin verebilirsin.",
    unsupported: "Bu tarayıcıda mikrofon kullanılamıyor.",
  },

  game: {
    round: (r, t) => `Tur ${r}/${t}`,
    introTitle: "Sıradaki",
    intro: (name) => `Sahnede: ${name}`,
    promptHint: (p) => `Öneri: ${p}`,
    performTitle: "Performans",
    performYou: "Bir ses çıkar ya da taklit yap!",
    performOther: (name) => `${name} ses kaydediyor…`,
    recordingBubble: "🎙️ kaydediyor…",
    mimicTitle: "Taklit zamanı",
    mimicYou: "Dinle ve aynısını yap!",
    mimicYouPerformer: "Herkes seni taklit ediyor!",
    listen: "Orijinali dinle",
    submittedCount: (a, b) => `${a}/${b} taklit geldi`,
    record: "Kaydet",
    stop: "Durdur",
    rerecord: "Tekrar kaydet",
    play: "Dinle",
    send: "Gönder",
    sent: "Gönderildi ✔ Diğerleri bekleniyor…",
    tooQuiet: "Ses çok kısa ya da çok sessiz, tekrar dene.",
    keysHint: "Boşluk: kaydet / durdur · Enter: gönder",
    resultTitle: "Tur sonucu",
    resultHeading: (name) => `${name} taklitleri`,
    skipped: "Tur atlandı — ses gelmedi.",
    original: "Orijinal",
    performerPoints: (p) => `Performans puanı +${p}`,
    notSubmitted: "Göndermedi",
    rhythm: "Ritim",
    pitch: "Melodi",
    tone: "Tını",
    rating: (score) =>
      score >= 85 ? "Mükemmel!" : score >= 70 ? "Çok iyi!" : score >= 50 ? "İyi" : score >= 30 ? "Fena değil" : "Pek benzemedi",
    scoreExplain:
      "Puan = ritim %40 + melodi %40 + tını %20. Sesinin ince ya da kalın olması önemli değil; önemli olan iniş-çıkışların ve vurguların aynı olması.",
  },

  results: {
    title: "Sonuçlar",
    winner: (name) => `Kazanan: ${name}!`,
    tie: "Berabere!",
    points: (p) => `${p} puan`,
    playAgain: "Tekrar oyna",
    waitingHost: "Host yeni oyunu başlatabilir.",
    leave: "Odadan çık",
  },

  connection: {
    connecting: "Bağlanıyor…",
    reconnecting: "Bağlantı koptu, yeniden bağlanılıyor…",
  },

  errors: {
    ROOM_NOT_FOUND: "Böyle bir oda yok (ya da süresi doldu).",
    ROOM_FULL: "Oda dolu (en fazla 6 kişi).",
    INVALID_NAME: "Takma ad 1–16 karakter olmalı.",
    INVALID_MESSAGE: "Bir şeyler ters gitti, tekrar dene.",
    INVALID_ACTION: "Bunu şu an yapamazsın.",
    NOT_HOST: "Bunu sadece host yapabilir.",
    NOT_ENOUGH_PLAYERS: "En az 2 oyuncu gerekli.",
    GAME_ALREADY_STARTED: "Oyun çoktan başladı.",
    INVALID_PHASE: "Bunun için artık geç.",
    ALREADY_SUBMITTED: "Zaten gönderdin.",
    RATE_LIMITED: "Biraz yavaş!",
    SESSION_EXPIRED: "Oturumun sona erdi.",
    CONNECTION_ERROR: "Sunucuya bağlanılamadı.",
    REPLACED: "Oyun başka bir sekmede açıldı.",
    MIC_DENIED: "Mikrofon izni verilmedi.",
    MIC_UNSUPPORTED: "Bu tarayıcıda mikrofon kullanılamıyor.",
    WEBGL: "Bu oyun 3D grafik (WebGL) gerektiriyor. Güncel Chrome, Edge ya da Firefox kullan.",
  },
};
